# Generated by Django 5.0.4 on 2024-04-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_ink',
            new_name='demo_link',
        ),
    ]
